<?php
$stock_halo_damage_tags=[
'weapons\assault rifle\bullet' => 'Assault Rifle',
'weapons\assault rifle\melee' => 'Assault Rifle Melee',
'weapons\pistol\bullet' => 'Pistol',
'weapons\pistol\melee' => 'Pistol Melee',
'globals\vehicle_collision' => 'Hit With Vehicle',
'globals\falling' => 'Falling',
'globals\distance' => 'Falling Very Far',
'weapons\plasma rifle\bolt' => 'Plasma Rifle',
'weapons\plasma rifle\melee' => 'Plasma Rifle Melee',
'weapons\shotgun\pellet' => 'Shotgun',
'weapons\shotgun\melee' => 'Shotgun Melee',
'weapons\sniper rifle\sniper bullet' => 'Sniper Rifle',
'weapons\sniper rifle\melee' => 'Sniper Rifle Melee',
'weapons\rocket launcher\explosion' => 'Rocket',
'weapons\rocket launcher\melee' => 'Rocket Launcher Melee',
'weapons\plasma_cannon\effects\plasma_cannon_explosion' => 'Fuel Rod Explosion',
'weapons\plasma_cannon\impact damage' => 'Fuel Rod Hit',
'weapons\plasma_cannon\effects\plasma_cannon_melee' => 'Fuel Rod Melee',
'weapons\flamethrower\impact damage' => 'Flamethrower Hit',
'weapons\flamethrower\explosion' => 'Flamethrower Burning',
'weapons\flamethrower\melee' => 'Flamethrower Melee',
'weapons\plasma pistol\bolt' => 'Plasma Pistol',
'weapons\plasma rifle\charged bolt' => 'Plasma Pistol Charged',
'weapons\plasma pistol\melee' => 'Plamsa Pistol Melee',
'weapons\flag\melee' => 'Flag Melee',
'weapons\ball\melee' => 'Oddball Melee',
'vehicles\scorpion\shell explosion' => 'Scorpion Shell',
'vehicles\scorpion\bullet' => 'Scorpion Chain Gun',
'vehicles\ghost\ghost bolt' => 'Ghost Bolt',
'vehicles\warthog\bullet' => 'Warthog Chain Gun',
'vehicles\banshee\banshee bolt' => 'Banshee Bolt',
'vehicles\banshee\mp_fuel rod explosion' => 'Banshee Fuel Rod',
'vehicles\c gun turret\mp bolt' => 'Gun Turret Bolt',
'weapons\needler\detonation damage' => 'Needler Bolt',
'weapons\needler\explosion' => 'Needler Explosion',
'weapons\needler\melee' => 'Needler Melee',
'weapons\frag grenade\explosion' => 'Frag Grenade',
'weapons\plasma grenade\attached' => 'Plasma Grenade Stuck',
'weapons\plasma grenade\explosion' => 'Plasma Grenade',
];

?>
